### ISSUE TITLE
UI/Main.py bug

### ISSUE THREAD

**Issue by Alireza-Alipanah** [sharif-ml-lab/IMDb-IR-System#10]
In the provided crawled data, directors and stars field can be None which results in NoneType exception in the following code section:
https://github.com/sharif-ml-lab/IMDb-IR-System/blob/ab4e92b6957fe747331744d815946b4eb6b57d90/UI/main.py#L173-L183

**Comment by amirhossein-razlighi** [comment]
You should handle this case in your crawled data. To solve this, simply you can pass an empty list (for example) for the `directors`. Then the `len` will be 0 and everything works correctly.
By the way, having `None` values in your main data (e.g. crawled data) which you are using in many occasions is not a good idea and requires such pre/post processings. If you have any further questions, please ask.
