### ISSUE TITLE
Problem with non existing keys used in the check_add_remove_is_correct() function in Logic/core/indexer.index.py 

### ISSUE THREAD

**Issue by MrTbag** [sharif-ml-lab/IMDb-IR-System#2]
https://github.com/sharif-ml-lab/IMDb-IR-System/blob/42cef6dca4495eb978558caaaf63cc4c401162fd/Logic/core/indexer/index.py#L132C19-L132C28

There is no guarantee that the keys introduced for the dummy_document already exist as keys in any of self.index's dictionaries. So statements such as 

```
index_before_add[Indexes.STARS.value]['tim']
```

could very well result in a KeyError. It would be essential that in this function which is aiming to verify the indexing of the documents, the new keys for the dummy_document be added(if needed) to the corresponding self.index dictionaries first; specially when the ```dict[key][value]``` syntax is utilized instead of the more reasonable ```dict.get(key)``` for such cases.

**Comment by amirhossein-razlighi** [comment]
Hi.
Thanks for opening this issue! I will check the validity of the issue and get back to you. please stay tuned!

**Comment by amirhossein-razlighi** [comment]
I assigned `Student` label to this issue. Whoever makes a valid PR sooner, will get the credits for this issue.
Thanks!
