### ISSUE TITLE
check_if_indexing_is_good test in idnex.py bug

### ISSUE THREAD

**Issue by Danial-Gharib** [sharif-ml-lab/IMDb-IR-System#3]
when you iterate over the words in document[index-type] existence if a word in a doc should not be checked like this as it is in the index.py:
`
for field in document[index_type]:
                if check_word in field:
                    docs.append(document['id'])
                    break
`
it should be like :
`
for field in document[index_type]:
                if check_word == field:
                    docs.append(document['id'])
                    break
`
because there could be some words even after preprocessing (stemming, etc.) that could start with the same meaningful first part but are two different words with different meaning in our index.

**Comment by amirhossein-razlighi** [comment]
Hi.
Thanks for opening this issue! I will check the validity of the issue and get back to you. please stay tuned!

**Comment by amirhossein-razlighi** [comment]
Sorry, but this issue seems invalid. Since `field` variable is of type `list` in many cases (e.g. field can be `genre` which is obviously a list), and thus, checking equality will check for equal instances and results in a wrong outcome!

Thanks again for mentioning that.
