### ISSUE TITLE
unigram

### ISSUE THREAD

**Issue by Davooddkareshki** [sharif-ml-lab/IMDb-IR-System#6]
سلام خسته نباشید.
برای مدل یونیگرام یک فایل برای ساخت cf_index هم باید وجود میداشت(من خودم دستی اضافه کردم). چون تعداد داده های داده شده نزدیک ۱۰ هزار تاست و نمیتوان موقع سرچ آن را حساب کرد(زمان زیادی طول میکشه).

**Comment by amirhossein-razlighi** [comment]
سلام. روش‌های دیگری هم برای رفع مشکل زمان زیاد وجود دارد. هرچند، انجام این روش‌ها بنابر نظر شما و ایده‌ی شماست (مثلا ساخت cf_index که گفتید). درنتیجه، لزومی به وجود و الزام یک روش مشخص در repo نیست. 
اگر مجددا سوال یا ابهامی هست، بفرمایید
